"""Shared dataset and formatting helpers for Lightning training pipelines."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import asdict
import json
import random
from typing import Any, Callable, Optional

from datasets import (
    Dataset,
    DatasetDict,
    IterableDataset,
    IterableDatasetDict,
    concatenate_datasets,
    interleave_datasets,
    load_dataset,
)
from lightning import LightningDataModule
from torch.utils.data import DataLoader

from lightning_grpo.data.converter import DatasetFormat, convert_sft_sample
from lightning_grpo.utils.data.utils import DatasetConfig, DatasetMixtureConfig
from lightning_grpo.utils.configs.base import DataConfig


class ConversationTemplate:
    """Convert row-based samples into chat-style message lists."""

    def __init__(
        self,
        prompt_column: str,
        response_column: str,
        messages_column: str = "messages",
        dataset_format: DatasetFormat | str = "auto",
        system_prompt: Optional[str] = None,
    ) -> None:
        self.prompt_column = prompt_column
        self.response_column = response_column
        self.messages_column = messages_column
        self.dataset_format = dataset_format
        self.system_prompt = system_prompt

    def __call__(self, sample: dict[str, Any]) -> dict[str, Any]:
        """Create a canonical message list for one sample."""

        converted = convert_sft_sample(sample, self.dataset_format)
        if not converted.get("messages"):
            raise KeyError(f"No chat messages could be built from sample using dataset_format='{self.dataset_format}'.")
        if self.system_prompt and not any(message.get("role") == "system" for message in converted["messages"]):
            converted = dict(converted)
            converted["messages"] = [{"role": "system", "content": self.system_prompt}, *converted["messages"]]
        return converted


SYSTEM_PROMPTS = [
    "你是一个知识丰富的AI，尽力为用户提供准确的信息。",
    "你是nekomind，一个小巧但有用的语言模型。",
    "你是一个专业的AI助手，请提供有价值的回答。",
    "你是nekomind，请尽力帮助用户解决问题。",
    "你是一个可靠的AI，请给出准确的回答。",
    "You are a helpful AI assistant.",
    "You are nekomind, a lightweight intelligent assistant.",
    "You are a friendly chatbot. Please answer the user's questions carefully.",
    "You are a knowledgeable AI. Try your best to provide accurate information.",
    "You are nekomind, a small but useful language model.",
]


def preprocess_chat_messages(
    messages: list[dict[str, Any]],
    add_system_ratio: float = 0.0,
) -> list[dict[str, Any]]:
    """Normalize chat messages while preserving tool-use samples."""

    normalized = [dict(message) for message in messages]
    if any(message.get("tools") for message in normalized):
        return normalized

    if normalized and normalized[0].get("role") != "system" and add_system_ratio > 0.0:
        if random.random() < add_system_ratio:
            normalized = [{"role": "system", "content": random.choice(SYSTEM_PROMPTS)}] + normalized
    return normalized


def postprocess_chat_text(text: str, empty_think_ratio: float = 1.0) -> str:
    """Optionally remove empty think tags generated by the chat template."""

    needle = "<think>\n\n</think>\n\n"
    if needle in text and random.random() > empty_think_ratio:
        return text.replace(needle, "")
    return text


def normalize_conversation_messages(messages: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], Any]:
    """Normalize message fields and extract tool definitions from system prompts."""

    normalized: list[dict[str, Any]] = []
    tools = None
    for message in messages:
        current = dict(message)
        if current.get("role") == "system" and current.get("tools"):
            tools = json.loads(current["tools"]) if isinstance(current["tools"], str) else current["tools"]
        if current.get("tool_calls") and isinstance(current["tool_calls"], str):
            current["tool_calls"] = json.loads(current["tool_calls"])
        normalized.append(current)
    return normalized, tools


class ChatTemplateProcessor:
    """Shared renderer/tokenizer for converter-normalized chat samples."""

    def __init__(self, tokenizer: Any) -> None:
        self.tokenizer = tokenizer

    @staticmethod
    def normalize_messages(messages: Any, row_tools: Any = None) -> tuple[list[dict[str, Any]], Any]:
        """Normalize message containers and resolve tool definitions."""

        if isinstance(messages, str):
            try:
                parsed_messages = json.loads(messages)
            except json.JSONDecodeError:
                parsed_messages = messages
        else:
            parsed_messages = messages

        if not isinstance(parsed_messages, list):
            parsed_messages = [parsed_messages]

        normalized: list[dict[str, Any]] = []
        tools = row_tools
        for message in parsed_messages:
            current = dict(message) if isinstance(message, Mapping) else {"role": "user", "content": message}
            current.setdefault("content", "")
            if current["content"] is None:
                current["content"] = ""
            if current.get("role") == "system" and current.get("tools") and tools is None:
                tools = current["tools"]
            normalized.append(current)
        return normalized, tools

    @staticmethod
    def should_add_generation_prompt(messages: list[dict[str, Any]], enabled: bool) -> bool:
        """Decide whether chat rendering should append a generation prompt."""

        return enabled and (not messages or messages[-1].get("role") != "assistant")

    def render(
        self,
        messages: list[dict[str, Any]],
        *,
        add_generation_prompt: bool = False,
        tools: Any = None,
        postprocess: bool = True,
        **chat_template_kwargs: Any,
    ) -> str:
        """Render messages to text with optional shared postprocessing."""

        text = apply_chat_template(
            tokenizer=self.tokenizer,
            messages=messages,
            add_generation_prompt=add_generation_prompt,
            tools=tools,
            **chat_template_kwargs,
        )
        return postprocess_chat_text(text) if postprocess else text

    def tokenize(
        self,
        messages: list[dict[str, Any]],
        *,
        add_generation_prompt: bool = False,
        tools: Any = None,
        max_length: int,
        return_assistant_tokens_mask: bool = False,
    ) -> dict[str, Any]:
        """Tokenize chat messages through tokenizer templates with a text fallback."""

        if hasattr(self.tokenizer, "apply_chat_template"):
            try:
                tokenized = self.tokenizer.apply_chat_template(
                    messages,
                    tokenize=True,
                    add_generation_prompt=add_generation_prompt,
                    tools=tools,
                    truncation=True,
                    max_length=max_length,
                    return_dict=True,
                    return_assistant_tokens_mask=return_assistant_tokens_mask,
                )
                if isinstance(tokenized, Mapping):
                    return dict(tokenized)
                if hasattr(tokenized, "keys"):
                    return {key: tokenized[key] for key in tokenized.keys()}
                return {"input_ids": list(tokenized), "attention_mask": [1] * len(tokenized)}
            except TypeError:
                pass

        text = self.render(
            messages,
            add_generation_prompt=add_generation_prompt,
            tools=tools,
        )
        tokenized = self.tokenizer(
            text,
            truncation=True,
            max_length=max_length,
            padding=False,
            add_special_tokens=False,
        )
        return {
            "input_ids": list(tokenized["input_ids"]),
            "attention_mask": list(tokenized["attention_mask"]),
        }

    def prepare_sample(self, sample: Mapping[str, Any]) -> tuple[list[dict[str, Any]], Any]:
        """Return messages and tools from a converted sample."""

        messages, tools = self.normalize_messages(sample["messages"], sample.get("tools"))
        return messages, tools


DEFAULT_VAL_SPLIT_NAME = "test"


def resolve_shuffle_state(data_config: DataConfig) -> bool:
    """Resolve DataLoader shuffle state from data configuration."""

    return bool(data_config.shuffle and not data_config.streaming)


def load_dataset_from_config(data_config: DataConfig) -> DatasetDict | IterableDatasetDict:
    """Load a dataset or dataset mixture from configuration."""

    streaming = data_config.streaming

    def _shuffle_streaming_dataset(dataset: IterableDataset) -> IterableDataset:
        """Apply buffer-based shuffle to a streaming dataset."""
        return dataset.shuffle(seed=data_config.split_seed, buffer_size=data_config.shuffle_buffer_size)

    def _load_single_dataset(dataset_config: DatasetConfig) -> DatasetDict | IterableDatasetDict:
        """Load one dataset from a nested dataset configuration."""
        kwargs: dict[str, Any] = {
            "cache_dir": data_config.cache_dir,
            "streaming": streaming,
        }
        if dataset_config.data_files is not None:
            kwargs["data_files"] = dataset_config.data_files
        return load_dataset(dataset_config.id, dataset_config.config, **kwargs)

    def _coerce_dataset_config(raw_config: DatasetConfig | Mapping[str, Any]) -> DatasetConfig:
        """Normalize a nested dataset entry into DatasetConfig."""

        if isinstance(raw_config, DatasetConfig):
            return raw_config
        if not isinstance(raw_config, Mapping):
            raise TypeError(f"dataset_mixture.datasets entries must be mappings, got {type(raw_config).__name__}.")
        return DatasetConfig(
            id=raw_config.get("id"),
            config=raw_config.get("config"),
            split=raw_config.get("split", data_config.train_split),
            data_files=raw_config.get("data_files"),
            columns=raw_config.get("columns"),
            weight=raw_config.get("weight"),
        )

    def _coerce_dataset_mixture(raw_mixture: DatasetMixtureConfig | Mapping[str, Any]) -> DatasetMixtureConfig:
        """Normalize dataset mixture configuration from YAML/dacite/dataclass values."""

        if isinstance(raw_mixture, DatasetMixtureConfig):
            raw_datasets = raw_mixture.datasets
            return DatasetMixtureConfig(
                datasets=[_coerce_dataset_config(dataset) for dataset in raw_datasets],
                seed=raw_mixture.seed,
                test_split_size=raw_mixture.test_split_size,
            )
        if not isinstance(raw_mixture, Mapping):
            raise TypeError(f"data.dataset_mixture must be a mapping, got {type(raw_mixture).__name__}.")
        raw_datasets = raw_mixture.get("datasets")
        if not isinstance(raw_datasets, list) or not raw_datasets:
            raise ValueError("data.dataset_mixture.datasets must be a non-empty list.")
        return DatasetMixtureConfig(
            datasets=[_coerce_dataset_config(dataset) for dataset in raw_datasets],
            seed=raw_mixture.get("seed", data_config.split_seed),
            test_split_size=raw_mixture.get("test_split_size"),
        )

    if data_config.dataset_mixture is not None:
        dataset_mixture = _coerce_dataset_mixture(data_config.dataset_mixture)
        all_splits: dict[str, list[Dataset | IterableDataset]] = {}
        for dataset_config in dataset_mixture.datasets:
            ds = _load_single_dataset(dataset_config)
            if dataset_config.split not in ds:
                raise ValueError(
                    f"Split '{dataset_config.split}' not found in dataset '{dataset_config.id}'. "
                    f"Available splits: {list(ds.keys())}"
                )
            split_dataset = ds[dataset_config.split]
            if dataset_config.columns is not None:
                split_dataset = split_dataset.select_columns(dataset_config.columns)
            if dataset_config.weight is not None and not streaming:
                split_dataset = split_dataset.shuffle(seed=dataset_mixture.seed).select(
                    range(int(len(split_dataset) * dataset_config.weight))
                )
            all_splits.setdefault(dataset_config.split, []).append(split_dataset)

        if streaming:
            dataset_dict = IterableDatasetDict({
                split: interleave_datasets(datasets)
                for split, datasets in all_splits.items()
            })
        else:
            dataset_dict = DatasetDict({
                split: concatenate_datasets(datasets)
                for split, datasets in all_splits.items()
            })
            for split in dataset_dict:
                dataset_dict[split] = dataset_dict[split].shuffle(seed=dataset_mixture.seed)

        if dataset_mixture.test_split_size is not None:
            if streaming:
                raise ValueError("data.dataset_mixture.test_split_size is not supported with streaming datasets.")
            if data_config.train_split not in dataset_dict:
                raise ValueError(
                    f"Cannot create a test split because train split '{data_config.train_split}' is missing."
                )
            dataset_dict = dataset_dict[data_config.train_split].train_test_split(
                test_size=dataset_mixture.test_split_size,
                seed=dataset_mixture.seed,
            )
    elif data_config.dataset_name:
        dataset_dict = _load_single_dataset(
            DatasetConfig(
                id=data_config.dataset_name,
                config=data_config.dataset_config,
                data_files=data_config.data_files,
            )
        )
    else:
        raise ValueError("Either data.dataset_name or data.dataset_mixture must be configured.")

    if data_config.train_split in dataset_dict and streaming and data_config.shuffle:
        dataset_dict[data_config.train_split] = _shuffle_streaming_dataset(
            dataset_dict[data_config.train_split]
        )

    return dataset_dict


def apply_chat_template(
    tokenizer: Any,
    messages: list[dict[str, str]],
    add_generation_prompt: bool = False,
    tools: Any = None,
    return_assistant_tokens_mask: bool = False,
    **chat_template_kwargs: Any,
) -> str:
    """Render messages into a training string with the tokenizer template."""

    if tokenizer.chat_template is None:
        rendered = []
        for message in messages:
            rendered.append(f"<{message['role']}>\n{message['content']}")
        if add_generation_prompt:
            rendered.append("<assistant>\n")
        return "\n".join(rendered)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
        tools=tools,
        return_assistant_tokens_mask=return_assistant_tokens_mask,
        **chat_template_kwargs,
    )


def dump_data_config(data_config: DataConfig) -> dict[str, Any]:
    """Serialize the data configuration for logging and checkpoint metadata."""

    return asdict(data_config)


class BaseDataModule(LightningDataModule):
    """Reusable base class for dataset-driven Lightning data modules."""

    def __init__(self, data_config: DataConfig) -> None:
        super().__init__()
        self.data_config = data_config
        self.train_dataset: Optional[Dataset | IterableDataset] = None
        self.val_dataset: Optional[Dataset | IterableDataset] = None

    def load_dataset_dict(self) -> DatasetDict | IterableDatasetDict:
        """Load the configured dataset dictionary."""

        return load_dataset_from_config(self.data_config)

    def resolve_val_split_name(self, dataset_dict: DatasetDict | IterableDatasetDict) -> Optional[str]:
        """Resolve the validation split name for the current dataset dictionary."""

        if self.data_config.val_split and self.data_config.val_split in dataset_dict:
            return self.data_config.val_split
        if DEFAULT_VAL_SPLIT_NAME in dataset_dict:
            return DEFAULT_VAL_SPLIT_NAME
        return None


    def map_dataset(
        self,
        dataset: Dataset | IterableDataset,
        preprocess_fn: Callable[[dict[str, list[Any]]], dict[str, list[Any]]],
        desc: str,
        **kwargs: Any,
    ) -> Dataset | IterableDataset:
        """Apply a shared batched dataset preprocessing transform."""

        if isinstance(dataset, IterableDataset):
            remove_columns = list(dataset.column_names) if dataset.column_names else None
            return dataset.map(
                preprocess_fn,
                batched=True,
                batch_size=self.data_config.preprocessing_batch_size,
                remove_columns=remove_columns,
                **kwargs,
            )

        return dataset.map(
            preprocess_fn,
            batched=True,
            batch_size=self.data_config.preprocessing_batch_size,
            num_proc=self.data_config.num_workers,
            remove_columns=list(dataset.column_names),
            load_from_cache_file=self.data_config.preprocessing_use_cache,
            keep_in_memory=self.data_config.preprocessing_keep_in_memory,
            desc=desc,
            **kwargs,
        )

    def _build_dataloader(
        self,
        dataset: Dataset | IterableDataset,
        batch_size: int,
        collate_fn: Callable[[list[dict[str, Any]]], Any],
        *,
        shuffle: bool,
        drop_last: bool,
    ) -> DataLoader:
        """Build a dataloader with shared worker and memory settings."""

        is_iterable = isinstance(dataset, IterableDataset)
        num_workers = 0 if is_iterable else self.data_config.num_workers
        return DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=False if is_iterable else shuffle,
            num_workers=num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            drop_last=drop_last,
        )


class ChatTemplateDataModule(BaseDataModule):
    """Base class for chat-style pipelines backed by `ConversationTemplate`."""

    def __init__(
        self,
        data_config: DataConfig,
        system_prompt: Optional[str] = None,
    ) -> None:
        super().__init__(data_config=data_config)
        self.system_prompt = system_prompt

    def build_conversation_template(self) -> ConversationTemplate:
        """Construct the row-to-messages formatter from chat data settings."""

        prompt_column = getattr(self.data_config, "prompt_column")
        response_column = getattr(self.data_config, "response_column")
        messages_column = getattr(self.data_config, "messages_column", "messages")
        dataset_format = getattr(self.data_config, "dataset_format", "auto")
        return ConversationTemplate(
            prompt_column=prompt_column,
            response_column=response_column,
            messages_column=messages_column,
            dataset_format=dataset_format,
            system_prompt=self.system_prompt,
        )

    @staticmethod
    def iter_batch_samples(batch: dict[str, list[Any]]) -> list[dict[str, Any]]:
        """Convert a dict-of-lists batch into a list of row dictionaries."""

        batch_size = len(next(iter(batch.values())))
        return [
            {key: value[index] for key, value in batch.items()}
            for index in range(batch_size)
        ]
