"""Shared dataset and formatting helpers for Lightning training pipelines."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import asdict
import json
import random
from typing import Any, Callable, Optional

from datasets import (
    Dataset,
    DatasetDict,
    IterableDataset,
    IterableDatasetDict,
    concatenate_datasets,
    interleave_datasets,
    load_dataset,
)
from lightning import LightningDataModule
from torch.utils.data import DataLoader

from lightning_grpo.utils.configs.base import DataConfig, DatasetConfig


class ConversationTemplate:
    """Convert row-based samples into chat-style message lists."""

    def __init__(
        self,
        prompt_column: str,
        response_column: str,
        messages_column: str = "messages",
        system_prompt: Optional[str] = None,
    ) -> None:
        self.prompt_column = prompt_column
        self.response_column = response_column
        self.messages_column = messages_column
        self.system_prompt = system_prompt

    def __call__(self, sample: dict[str, Any]) -> dict[str, Any]:
        """Create a canonical message list for one sample."""

        if self.messages_column in sample and sample[self.messages_column] is not None:
            return {"messages": sample[self.messages_column]}
        if "conversations" in sample and sample["conversations"] is not None:
            return {"messages": sample["conversations"]}

        messages: list[dict[str, str]] = []
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})

        if self.prompt_column not in sample:
            raise KeyError(f"Prompt column '{self.prompt_column}' not found in sample.")

        messages.append({"role": "user", "content": str(sample[self.prompt_column])})
        if self.response_column in sample and sample[self.response_column] is not None:
            messages.append({"role": "assistant", "content": str(sample[self.response_column])})
        return {"messages": messages}


SYSTEM_PROMPTS = [
    "你是一个知识丰富的AI，尽力为用户提供准确的信息。",
    "你是nekomind，一个小巧但有用的语言模型。",
    "你是一个专业的AI助手，请提供有价值的回答。",
    "你是nekomind，请尽力帮助用户解决问题。",
    "你是一个可靠的AI，请给出准确的回答。",
    "You are a helpful AI assistant.",
    "You are nekomind, a lightweight intelligent assistant.",
    "You are a friendly chatbot. Please answer the user's questions carefully.",
    "You are a knowledgeable AI. Try your best to provide accurate information.",
    "You are nekomind, a small but useful language model.",
]


def iter_batch_samples(batch: dict[str, list[Any]]) -> list[dict[str, Any]]:
    """Convert a dict-of-lists batch into a list of row dictionaries."""

    batch_size = len(next(iter(batch.values())))
    return [
        {key: value[index] for key, value in batch.items()}
        for index in range(batch_size)
    ]


def preprocess_chat_messages(
    messages: list[dict[str, Any]],
    add_system_ratio: float = 0.0,
) -> list[dict[str, Any]]:
    """Normalize chat messages while preserving tool-use samples."""

    normalized = [dict(message) for message in messages]
    if any(message.get("tools") for message in normalized):
        return normalized

    if normalized and normalized[0].get("role") != "system" and add_system_ratio > 0.0:
        if random.random() < add_system_ratio:
            normalized = [{"role": "system", "content": random.choice(SYSTEM_PROMPTS)}] + normalized
    return normalized


def postprocess_chat_text(text: str, empty_think_ratio: float = 1.0) -> str:
    """Optionally remove empty think tags generated by the chat template."""

    needle = "<think>\n\n</think>\n\n"
    if needle in text and random.random() > empty_think_ratio:
        return text.replace(needle, "")
    return text


def normalize_conversation_messages(messages: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], Any]:
    """Normalize message fields and extract tool definitions from system prompts."""

    normalized: list[dict[str, Any]] = []
    tools = None
    for message in messages:
        current = dict(message)
        if current.get("role") == "system" and current.get("tools"):
            tools = json.loads(current["tools"]) if isinstance(current["tools"], str) else current["tools"]
        if current.get("tool_calls") and isinstance(current["tool_calls"], str):
            current["tool_calls"] = json.loads(current["tool_calls"])
        normalized.append(current)
    return normalized, tools


class ChatTemplateProcessor:
    """Shared renderer/tokenizer for converter-normalized chat samples."""

    def __init__(self, tokenizer: Any) -> None:
        self.tokenizer = tokenizer

    @staticmethod
    def normalize_messages(messages: Any, row_tools: Any = None) -> tuple[list[dict[str, Any]], Any]:
        """Normalize message containers and resolve tool definitions."""

        if isinstance(messages, str):
            try:
                parsed_messages = json.loads(messages)
            except json.JSONDecodeError:
                parsed_messages = messages
        else:
            parsed_messages = messages

        if not isinstance(parsed_messages, list):
            parsed_messages = [parsed_messages]

        normalized: list[dict[str, Any]] = []
        tools = row_tools
        for message in parsed_messages:
            current = dict(message) if isinstance(message, Mapping) else {"role": "user", "content": message}
            current.setdefault("content", "")
            if current["content"] is None:
                current["content"] = ""
            if current.get("role") == "system" and current.get("tools") and tools is None:
                tools = current["tools"]
            normalized.append(current)
        return normalized, tools

    @staticmethod
    def should_add_generation_prompt(messages: list[dict[str, Any]], enabled: bool) -> bool:
        """Decide whether chat rendering should append a generation prompt."""

        return enabled and (not messages or messages[-1].get("role") != "assistant")

    def render(
        self,
        messages: list[dict[str, Any]],
        *,
        add_generation_prompt: bool = False,
        tools: Any = None,
        postprocess: bool = True,
        empty_think_ratio: float = 1.0,
        **chat_template_kwargs: Any,
    ) -> str:
        """Render messages to text with optional shared postprocessing."""

        text = apply_chat_template(
            tokenizer=self.tokenizer,
            messages=messages,
            add_generation_prompt=add_generation_prompt,
            tools=tools,
            **chat_template_kwargs,
        )
        return postprocess_chat_text(text, empty_think_ratio) if postprocess else text

    def tokenize(
        self,
        messages: list[dict[str, Any]],
        *,
        add_generation_prompt: bool = False,
        tools: Any = None,
        max_length: int,
        return_assistant_tokens_mask: bool = False,
        empty_think_ratio: float = 1.0,
    ) -> dict[str, Any]:
        """Tokenize chat messages through tokenizer templates with a text fallback."""

        if hasattr(self.tokenizer, "apply_chat_template"):
            try:
                tokenized = self.tokenizer.apply_chat_template(
                    messages,
                    tokenize=True,
                    add_generation_prompt=add_generation_prompt,
                    tools=tools,
                    truncation=True,
                    max_length=max_length,
                    return_dict=True,
                    return_assistant_tokens_mask=return_assistant_tokens_mask,
                )
                if isinstance(tokenized, Mapping):
                    return dict(tokenized)
                if hasattr(tokenized, "keys"):
                    return {key: tokenized[key] for key in tokenized.keys()}
                return {"input_ids": list(tokenized), "attention_mask": [1] * len(tokenized)}
            except TypeError:
                pass

        text = self.render(
            messages,
            add_generation_prompt=add_generation_prompt,
            tools=tools,
            empty_think_ratio=empty_think_ratio,
        )
        tokenized = self.tokenizer(
            text,
            truncation=True,
            max_length=max_length,
            padding=False,
            add_special_tokens=False,
        )
        return {
            "input_ids": list(tokenized["input_ids"]),
            "attention_mask": list(tokenized["attention_mask"]),
        }

    def prepare_sample(
        self,
        sample: Mapping[str, Any],
        *,
        messages_column: str = "messages",
        tools_column: str = "tools",
    ) -> tuple[list[dict[str, Any]], Any]:
        """Return messages and tools from a converted sample."""

        messages, tools = self.normalize_messages(sample[messages_column], sample.get(tools_column))
        return messages, tools


DEFAULT_VAL_SPLIT_NAME = "test"


def resolve_shuffle_state(data_config: DataConfig) -> bool:
    """Resolve DataLoader shuffle state from data configuration."""

    return bool(data_config.shuffle and not data_config.streaming)


def load_dataset_from_config(data_config: DataConfig) -> DatasetDict | IterableDatasetDict:
    """Load a dataset or dataset mixture from configuration."""

    def _shuffle_streaming_dataset(dataset: IterableDataset) -> IterableDataset:
        """Apply buffer-based shuffle to a streaming dataset."""
        return dataset.shuffle(seed=data_config.split_seed, buffer_size=data_config.shuffle_buffer_size)

    def _load_single_dataset(dataset_config: DatasetConfig) -> DatasetDict | IterableDatasetDict:
        """Load one dataset from a nested dataset configuration."""
        kwargs: dict[str, Any] = {
            "cache_dir": data_config.cache_dir,
            "streaming": data_config.streaming,
        }
        if dataset_config.data_files is not None:
            kwargs["data_files"] = dataset_config.data_files
        if dataset_config.columns is not None:
            kwargs["columns"] = dataset_config.columns
        return load_dataset(dataset_config.id, dataset_config.config, **kwargs)

    if data_config.dataset_list is not None:
        datasets_train: list[Dataset | IterableDataset] = []
        datasets_val: list[Dataset | IterableDataset] = []
        weights: list[float] = []

        train_split = data_config.train_split
        val_split = data_config.val_split

        for dataset_config in data_config.dataset_list:
            ds_dict = _load_single_dataset(dataset_config)

            has_train = train_split in ds_dict
            has_val = val_split in ds_dict if val_split else False

            def _select_columns(ds: Dataset | IterableDataset) -> Dataset | IterableDataset:
                """Apply column selection if configured."""
                if dataset_config.columns and hasattr(ds, "column_names") and ds.column_names:
                    existing_cols = set(ds.column_names)
                    target_cols = [c for c in dataset_config.columns if c in existing_cols]
                    if target_cols and set(target_cols) != existing_cols:
                        return ds.select_columns(target_cols)
                return ds

            if has_train:
                datasets_train.append(_select_columns(ds_dict[train_split]))
                weights.append(dataset_config.weight if dataset_config.weight is not None else 1.0)

            if has_val:
                datasets_val.append(_select_columns(ds_dict[val_split]))

            # If neither train nor val split matched, fall back to the configured split or first available
            if not has_train and not has_val:
                split_name = dataset_config.split or train_split
                if split_name in ds_dict:
                    ds = ds_dict[split_name]
                else:
                    available = list(ds_dict.keys())
                    ds = ds_dict[available[0]]
                datasets_train.append(_select_columns(ds))
                weights.append(dataset_config.weight if dataset_config.weight is not None else 1.0)

        # Combine training datasets
        all_default_weights = all(w == 1.0 for w in weights)

        if len(datasets_train) == 0:
            combined_train = None
        elif len(datasets_train) == 1:
            combined_train = datasets_train[0]
        elif all_default_weights:
            combined_train = concatenate_datasets(datasets_train)
        else:
            total_weight = sum(weights)
            probabilities = [w / total_weight for w in weights]
            combined_train = interleave_datasets(
                datasets_train,
                probabilities=probabilities,
                seed=data_config.split_seed,
                stopping_strategy="all_exhausted",
            )

        # Combine validation datasets
        combined_val = None
        if datasets_val:
            combined_val = datasets_val[0] if len(datasets_val) == 1 else concatenate_datasets(datasets_val)

        # Build the final dataset dict
        splits: dict[str, Dataset | IterableDataset] = {}
        if combined_train is not None:
            if data_config.streaming and all_default_weights and data_config.shuffle:
                combined_train = _shuffle_streaming_dataset(combined_train)
            splits[train_split] = combined_train
        if combined_val is not None and val_split:
            splits[val_split] = combined_val

        if data_config.streaming:
            dataset_dict = IterableDatasetDict(splits)
        else:
            dataset_dict = DatasetDict(splits)

    elif data_config.dataset_name:
        dataset_dict = _load_single_dataset(
            DatasetConfig(
                id=data_config.dataset_name,
                config=data_config.dataset_config,
                data_files=data_config.data_files,
            )
        )
        if data_config.train_split in dataset_dict and data_config.streaming and data_config.shuffle:
            dataset_dict[data_config.train_split] = _shuffle_streaming_dataset(
                dataset_dict[data_config.train_split]
            )
    else:
        raise ValueError("Either data.dataset_name or data.dataset_list must be configured.")

    return dataset_dict


def apply_chat_template(
    tokenizer: Any,
    messages: list[dict[str, str]],
    add_generation_prompt: bool = False,
    tools: Any = None,
    return_assistant_tokens_mask: bool = False,
    **chat_template_kwargs: Any,
) -> str:
    """Render messages into a training string with the tokenizer template."""

    if tokenizer.chat_template is None:
        rendered = []
        for message in messages:
            rendered.append(f"<{message['role']}>\n{message['content']}")
        if add_generation_prompt:
            rendered.append("<assistant>\n")
        return "\n".join(rendered)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
        tools=tools,
        return_assistant_tokens_mask=return_assistant_tokens_mask,
        **chat_template_kwargs,
    )


def dump_data_config(data_config: DataConfig) -> dict[str, Any]:
    """Serialize the data configuration for logging and checkpoint metadata."""

    return asdict(data_config)


class BaseDataModule(LightningDataModule):
    """Reusable base class for dataset-driven Lightning data modules."""

    def __init__(self, data_config: DataConfig) -> None:
        super().__init__()
        self.data_config = data_config
        self.train_dataset: Optional[Dataset | IterableDataset] = None
        self.val_dataset: Optional[Dataset | IterableDataset] = None

    def load_dataset_dict(self) -> DatasetDict | IterableDatasetDict:
        """Load the configured dataset dictionary."""

        return load_dataset_from_config(self.data_config)

    def resolve_val_split_name(self, dataset_dict: DatasetDict | IterableDatasetDict) -> Optional[str]:
        """Resolve the validation split name for the current dataset dictionary."""

        if self.data_config.val_split and self.data_config.val_split in dataset_dict:
            return self.data_config.val_split
        if DEFAULT_VAL_SPLIT_NAME in dataset_dict:
            return DEFAULT_VAL_SPLIT_NAME
        return None


    def map_dataset(
        self,
        dataset: Dataset | IterableDataset,
        preprocess_fn: Callable[[dict[str, list[Any]]], dict[str, list[Any]]],
        desc: str,
        **kwargs: Any,
    ) -> Dataset | IterableDataset:
        """Apply a shared batched dataset preprocessing transform."""

        if isinstance(dataset, IterableDataset):
            remove_columns = list(dataset.column_names) if dataset.column_names else None
            return dataset.map(
                preprocess_fn,
                batched=True,
                batch_size=self.data_config.preprocessing_batch_size,
                remove_columns=remove_columns,
                **kwargs,
            )

        return dataset.map(
            preprocess_fn,
            batched=True,
            batch_size=self.data_config.preprocessing_batch_size,
            num_proc=self.data_config.num_workers,
            remove_columns=list(dataset.column_names),
            load_from_cache_file=self.data_config.preprocessing_use_cache,
            keep_in_memory=self.data_config.preprocessing_keep_in_memory,
            desc=desc,
            **kwargs,
        )

    def _build_dataloader(
        self,
        dataset: Dataset | IterableDataset,
        batch_size: int,
        collate_fn: Callable[[list[dict[str, Any]]], Any],
        *,
        shuffle: bool,
        drop_last: bool,
    ) -> DataLoader:
        """Build a dataloader with shared worker and memory settings."""

        is_iterable = isinstance(dataset, IterableDataset)
        num_workers = 0 if is_iterable else self.data_config.num_workers
        return DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=False if is_iterable else shuffle,
            num_workers=num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            drop_last=drop_last,
        )


class ChatTemplateDataModule(BaseDataModule):
    """Base class for chat-style pipelines backed by `ConversationTemplate`."""

    def __init__(
        self,
        data_config: DataConfig,
        system_prompt: Optional[str] = None,
    ) -> None:
        super().__init__(data_config=data_config)
        self.system_prompt = system_prompt

    def build_conversation_template(self) -> ConversationTemplate:
        """Construct the row-to-messages formatter from chat data settings."""

        prompt_column = getattr(self.data_config, "prompt_column")
        response_column = getattr(self.data_config, "response_column")
        messages_column = getattr(self.data_config, "messages_column", "messages")
        return ConversationTemplate(
            prompt_column=prompt_column,
            response_column=response_column,
            messages_column=messages_column,
            system_prompt=self.system_prompt,
        )
