"""Shared dataset and formatting helpers for the Lightning GRPO pipeline."""

from __future__ import annotations

from dataclasses import asdict
import json
import random
from typing import Any, Optional

from datasets import Dataset, DatasetDict, concatenate_datasets, load_dataset

from lightning_grpo.utils.configs.base import DataConfig, DatasetSource, ModelConfig


class ConversationTemplate:
    """Convert row-based samples into chat-style message lists."""

    def __init__(
            self,
            prompt_column: str,
            response_column: str,
            messages_column: str = "messages",
            system_prompt: Optional[str] = None,
    ) -> None:
        self.prompt_column = prompt_column
        self.response_column = response_column
        self.messages_column = messages_column
        self.system_prompt = system_prompt

    def __call__(self, sample: dict[str, Any]) -> dict[str, Any]:
        """Create a canonical message list for one sample."""

        if self.messages_column in sample and sample[self.messages_column] is not None:
            return {"messages": sample[self.messages_column]}

        messages: list[dict[str, str]] = []
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})

        if self.prompt_column not in sample:
            raise KeyError(f"Prompt column '{self.prompt_column}' not found in sample.")

        messages.append({"role": "user", "content": str(sample[self.prompt_column])})
        if self.response_column in sample and sample[self.response_column] is not None:
            messages.append({"role": "assistant", "content": str(sample[self.response_column])})
        return {"messages": messages}


SYSTEM_PROMPTS = [
    "你是一个知识丰富的AI，尽力为用户提供准确的信息。",
    "你是minimind，一个小巧但有用的语言模型。",
    "你是一个专业的AI助手，请提供有价值的回答。",
    "你是minimind，请尽力帮助用户解决问题。",
    "你是一个可靠的AI，请给出准确的回答。",
    "You are a helpful AI assistant.",
    "You are minimind, a lightweight intelligent assistant.",
    "You are a friendly chatbot. Please answer the user's questions carefully.",
    "You are a knowledgeable AI. Try your best to provide accurate information.",
    "You are minimind, a small but useful language model.",
]


def preprocess_chat_messages(
        messages: list[dict[str, Any]],
        add_system_ratio: float = 0.0,
) -> list[dict[str, Any]]:
    """Normalize chat messages while preserving tool-use samples."""

    normalized = [dict(message) for message in messages]
    if any(message.get("tools") for message in normalized):
        return normalized

    if normalized and normalized[0].get("role") != "system" and add_system_ratio > 0.0:
        if random.random() < add_system_ratio:
            normalized = [{"role": "system", "content": random.choice(SYSTEM_PROMPTS)}] + normalized
    return normalized


def postprocess_chat_text(text: str, empty_think_ratio: float = 1.0) -> str:
    """Optionally remove empty think tags generated by the chat template."""

    needle = "<think>\n\n</think>\n\n"
    if needle in text and random.random() > empty_think_ratio:
        return text.replace(needle, "")
    return text


def normalize_conversation_messages(messages: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], Any]:
    """Normalize message fields and extract tool definitions from system prompts."""

    normalized: list[dict[str, Any]] = []
    tools = None
    for message in messages:
        current = dict(message)
        if current.get("role") == "system" and current.get("tools"):
            tools = json.loads(current["tools"]) if isinstance(current["tools"], str) else current["tools"]
        if current.get("tool_calls") and isinstance(current["tool_calls"], str):
            current["tool_calls"] = json.loads(current["tool_calls"])
        normalized.append(current)
    return normalized, tools


DEFAULT_VAL_SPLIT_NAME = "test"


def _load_single_dataset(source: DatasetSource, seed: int) -> Dataset:
    """Load one dataset source from the Hugging Face hub."""

    dataset = load_dataset(source.path, source.config_name, split=source.split)
    if source.columns:
        dataset = dataset.select_columns(source.columns)
    if source.weight < 1.0:
        sample_size = max(1, int(len(dataset) * source.weight))
        dataset = dataset.shuffle(seed=seed).select(range(sample_size))
    return dataset


def _with_optional_validation_split(dataset_dict: DatasetDict, data_config: DataConfig) -> DatasetDict:
    """Add a derived validation split when requested and one is not already present."""

    existing_val_split = resolve_validation_split_name(data_config, dataset_dict)
    if existing_val_split is not None or data_config.val_split_size is None:
        return dataset_dict

    if data_config.train_split not in dataset_dict:
        raise KeyError(f"Train split '{data_config.train_split}' not found in dataset.")

    split_dataset = dataset_dict[data_config.train_split].train_test_split(
        test_size=data_config.val_split_size,
        seed=data_config.split_seed,
    )
    dataset_dict[data_config.train_split] = split_dataset["train"]
    dataset_dict[DEFAULT_VAL_SPLIT_NAME] = split_dataset["test"]
    return dataset_dict


def resolve_validation_split_name(data_config: DataConfig, dataset_dict: DatasetDict) -> Optional[str]:
    """Resolve which validation split should be used for the current dataset config."""

    if data_config.val_split and data_config.val_split in dataset_dict:
        return data_config.val_split
    if data_config.val_split_size is not None and DEFAULT_VAL_SPLIT_NAME in dataset_dict:
        return DEFAULT_VAL_SPLIT_NAME
    return None


def load_dataset_from_config(data_config: DataConfig) -> DatasetDict:
    """Load a dataset or dataset mixture from configuration."""

    if data_config.dataset_mixture:
        datasets = [_load_single_dataset(source, seed=data_config.split_seed) for source in data_config.dataset_mixture]
        combined_dataset = concatenate_datasets(datasets).shuffle(seed=data_config.split_seed)
        dataset_dict = DatasetDict({data_config.train_split: combined_dataset})
    elif data_config.dataset_name:
        dataset_dict = load_dataset(data_config.dataset_name, data_config.dataset_config)
    else:
        raise ValueError("Either dataset_name or dataset_mixture must be configured.")

    return _with_optional_validation_split(dataset_dict, data_config)


def apply_chat_template(
        tokenizer: Any,
        messages: list[dict[str, str]],
        add_generation_prompt: bool = False,
    tools: Any = None,
    return_assistant_tokens_mask: bool = False,
    **chat_template_kwargs: Any,
) -> str:
    """Render messages into a training string with the tokenizer template."""

    if tokenizer.chat_template is None:
        rendered = []
        for message in messages:
            rendered.append(f"<{message['role']}>\n{message['content']}")
        if add_generation_prompt:
            rendered.append("<assistant>\n")
        return "\n".join(rendered)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
        tools=tools,
        return_assistant_tokens_mask=return_assistant_tokens_mask,
        **chat_template_kwargs,
    )


def dump_data_config(data_config: DataConfig) -> dict[str, Any]:
    """Serialize the data configuration for logging and checkpoint metadata."""

    return asdict(data_config)
